apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-webflux-deployment
spec:
  template:
    metadata:
      name: with-webflux
      labels:
        app: with-webflux
    spec:
      containers:
        - name: with-webflux-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 8080
#          envFrom:
#            - configMapRef:
#                name: db-configmap
  selector:
    matchLabels:
      app: with-webflux
